### ISSUE TITLE
Can not authorize the app.

### ISSUE THREAD

**Issue by farishkash** [alinawww/Jamming#1]
I am trying to find what is causing this but somewhere there is a script that spotify doesn't like.  Screenshot below.

![authorize_-_spotify](https://user-images.githubusercontent.com/5844161/33044836-5d3b60c8-cdff-11e7-9f81-d39ef9efb617.jpg)

**Comment by alinawww** [comment]
Hey, that's strange. I am not having the same issue, but i just changed the `redirectUri` from the surge url to localhost:3000. Is that fixing it on your side?

**Comment by farishkash** [comment]
It is weird. I changed it and same issue.

I am going to wrap up the review tonight my time.

**Comment by alinawww** [comment]
Hey, I finally managed to reproduce this bug, after clearing all the browsing data. However, if I refresh, it just goes away and I can't log in. I can't imagine what the problem is, but I'll keep researching. I also tried another colleague's code just to see if I'm the only one, and I got the same error. I'll research further and I'll get to the bottom of this.

**Comment by alinawww** [comment]
The error I get is a bit different actually. See below. Could you maybe give me a few more details to help debug?

<img width="1181" alt="screen shot 2017-11-21 at 20 19 46" src="https://user-images.githubusercontent.com/13662674/33095574-6b5140e6-cf04-11e7-87cb-1d7ef7f4572d.png">
