### ISSUE TITLE
Playlist.js and functional stateless components.

### ISSUE THREAD

**Issue by farishkash** [alinawww/Jamming#2]
Unfortunately I still can't access this because I really wanted to play with this approach.

Great idea in doing this, in fact you maybe only the second person I have talked to about using FSC in this project.

First I have a  concern on the code below. Did this work properly? This isn't a one line statement so I do not see how  it could work without a return being added.  Implicit returns should work on this but if it did that is great.

```
const TrackList = (props: {tracks: Array<Object>, handleTrackAction: Function, isSearchResult: boolean}) => (
    <div className="TrackList">
        {props.tracks.map((track, index) => <Track key={index} track={track} handleTrackAction={props.handleTrackAction} isSearchResult={props.isSearchResult} />)}
    </div>
)
```

Second I understand why you were pulling from props but the format is hard to read and very expansive.  I think destructing is more readable and a cleaner approach while still achieving the same goal.  

```
const TrackList = props => {
  const { tracks, handleTrackAction, isSearchResult, ...other } = this.props;
  return (
    <div className="TrackList">
      {tracks.map((track, index) => (
        <Track
          key={index}
          track={track}
          handleTrackAction={handleTrackAction}
          isSearchResult={isSearchResult}
        />
      ))}
    </div>
  );
};
```

**Comment by alinawww** [comment]
Hey thanks for the evaluation and again, sorry that you couldn't run it. About the FSC, I can confirm that the code runs properly. It works with or without the parentheses, regardless of it being one or more lines.  As far as I know, you only need curly brackets when you need some js expression before the return, but since these are pure / dumb / stateless components, they don need any of that.

Regarding the props destructing, I agree with you. It looks much cleaner :) I should be more tidy in my code. Thanks!
